Added Open-Ended Evaluation
dsi-clinical-llm/clinical-llm-evaluation pull request #11
Opened 2023-12-05 04:23 UTC by niuyizhan

2023-12-06 22:06 UTC, ChaoPang commented on evaluations/qa/medquad_evaluator.py
> +
I am not sure if you need this custom metric since you are using the standard rogue, bleu and meteor

2023-12-06 22:06 UTC, ChaoPang commented on evaluations/qa/medquad_evaluator.py
> +        return match_score + mismatch_score
I am not sure if you need this custom metric since you are using the standard rogue, bleu and meteor

```suggestion
```

2023-12-06 22:08 UTC, ChaoPang commented on evaluations/hallucination/medquad_hallucination_evaluator.py
> +        return {'point_wise_score': normalized_score}
Similarly, I don't think `PointWiseScore` is used anywhere.
```Suggestion
```

2023-12-06 22:10 UTC, ChaoPang commented on prompt_templates/qa/qa_prompt.py
> +
Could you move the MedQuAD prompts to a separate module?

2023-12-06 22:12 UTC, ChaoPang requested changes
I don't think the runner is included in this PR.

2023-12-08 05:19 UTC, niuyizhan commented
I have updated the runner file to the niuyizhan-patch-1 branch, changed closed_book_qa_prompt to a separate file, and changed medquad_evaluator file correspondingly!

2023-12-10 03:12 UTC, ChaoPang commented
@niuyizhan I don't think you need a separate evaluator for hallucination because the prompt is the same as the closed-book prompt. You could add two additional hallucination metrics to the MedQuAD evaluator. I have a separate evaluator for PubmedQA because the pubmedqa hallucination prompt is designed to solicit hallucinated content. I will accept the PR, please open a new PR to remove `medquad_hallucination_evaluator` and moved its two hallucination metrics to `medquad_evaluator`

2023-12-10 03:12 UTC, ChaoPang approved these changes

2023-12-10 03:12 UTC, merged

2023-12-10 03:15 UTC, niuyizhan commented
Sure thing, thanks for the advice Chao.